server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: product-management
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG